import { Hono } from 'hono';
import { createAdminRouter } from './controllers/admin.controller.js';
import { AdminService } from './services/admin.service.js';
import { InMemoryAdminRepository } from './repositories/admin.repository.js';
import { createCollectionRouter } from './controllers/collection.controller.js';
import { CollectionService } from './services/collection.service.js';
import { InMemoryCollectionRepository } from './repositories/collection.repository.js';
import { createQuestionRouter } from './controllers/question.controller.js';
import { QuestionService } from './services/question.service.js';
import { InMemoryQuestionRepository } from './repositories/question.repository.js';
import { createSectionRouter } from './controllers/section.controller.js';
import { SectionService } from './services/section.service.js';
import { InMemorySectionRepository } from './repositories/section.repository.js';
import { createFormRouter } from './controllers/form.controller.js';
import { FormService } from './services/form.service.js';
import { InMemoryFormRepository } from './repositories/form.repository.js';
import { createFormulaRouter } from './controllers/formula.controller.js';
import { FormulaService } from './services/formula.service.js';
import { InMemoryFormulaRepository } from './repositories/formula.repository.js';

const adminRepository = new InMemoryAdminRepository();
const adminService = new AdminService(adminRepository);
const collectionRepository = new InMemoryCollectionRepository();
const collectionService = new CollectionService(collectionRepository);
const questionRepository = new InMemoryQuestionRepository();
const questionService = new QuestionService(questionRepository);
const sectionRepository = new InMemorySectionRepository();
const sectionService = new SectionService(sectionRepository, questionRepository);
const formRepository = new InMemoryFormRepository();
const formService = new FormService(formRepository, sectionRepository);
const formulaRepository = new InMemoryFormulaRepository();
const formulaService = new FormulaService(formulaRepository, questionRepository);

const router = new Hono();
router.route('/', createAdminRouter(adminService));
router.route('/collections', createCollectionRouter(collectionService));
router.route('/questions', createQuestionRouter(questionService));
router.route('/sections', createSectionRouter(sectionService));
router.route('/forms', createFormRouter(formService));
router.route('/formulas', createFormulaRouter(formulaService));
export default router;
